POST http://localhost:3000/todos
Content-Type: application/json

{
    "name":"naveen",
    "description":"topper"
}

###
PUT http://localhost:8000/todos
Content-Type: application/json

{

    "title":"kajj",
    "description":"love praveen"
}
###
DELETE http://localhost:3000/todos/66376c1ffc5417a4a8e279f1
